name: "Terraform Branch Deployment Flow"

on:
  push:
    branches:
      - test   # Triggers immediately when you push code to the test branch

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    name: "1. Run Terraform Plan"
    runs-on: ubuntu-latest
    outputs:
      # This allows us to pass configuration status to the next job
      plan_status: ${{ job.status }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.4"
          teffaform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Show AWS Caller Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init
        working-directory: "./S3 bucket"

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: "./S3 bucket"

  terraform_apply:
    name: "2. Await Approval & Apply"
    needs: terraform_plan                       # Ensures plan finishes first
    runs-on: ubuntu-latest
    environment: production                     # Activates the manual approval gate rule
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.4"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Show AWS Caller Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init
        working-directory: "./S3 bucket"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: "./S3 bucket"